### ISSUE TITLE
[Bug]在“在一个非套接字上尝试了一个操作。”后直接退出程序了

### ISSUE THREAD

**Issue by I-love-study** [GraiaProject/Ariadne#15]
**问题**
```
--- Logging error ---
--- Logging error ---
2021-11-10 23:58:18.436 | ERROR    | graia.ariadne.util:loguru_excepthook:64 - Uncaught Exception:
Traceback (most recent call last):

  File "D:\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle _ProactorBasePipeTransport._call_connection_lost(None)>

  File "D:\Python39\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
    │    │     │        │      └ 2
    │    │     │        └ <module 'socket' from 'D:\\Python39\\lib\\socket.py'>
    │    │     └ <method 'shutdown' of '_socket.socket' objects>
    │    └ <socket.socket fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
    └ <_ProactorSocketTransport closing fd=-1>

OSError: [WinError 10038] 在一个非套接字上尝试了一个操作。


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\Python39\lib\logging\__init__.py", line 1083, in emit
    msg = self.format(record)
          │    │      └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1738, "Exception in callback _ProactorBasePipeTransport._cal...
          │    └ <function Handler.format at 0x0000020E516DF310>
          └ <_StderrHandler <stderr> (WARNING)>

  File "D:\Python39\lib\logging\__init__.py", line 927, in format
    return fmt.format(record)
           │   │      └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1738, "Exception in callback _ProactorBasePipeTransport._cal...
           │   └ <function Formatter.format at 0x0000020E516E1670>
           └ <logging.Formatter object at 0x0000020E51642940>

  File "D:\Python39\lib\logging\__init__.py", line 671, in format
    record.exc_text = self.formatException(record.exc_info)
    │      │          │    │               │      └ (<class 'OSError'>, OSError(10038, '在一个非套接字上尝试了一个操作。', None, 10038, None), <traceback object at 0x0000020E575F7500>)
    │      │          │    │               └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1738, "Exception in callback _ProactorBasePipeTransport._cal...
    │      │          │    └ <function Formatter.formatException at 0x0000020E516E1430>
    │      │          └ <logging.Formatter object at 0x0000020E51642940>
    │      └ None
    └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1738, "Exception in callback _ProactorBasePipeTransport._cal...

  File "D:\Python39\lib\logging\__init__.py", line 621, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
    │         │               │      │      │         └ <_io.StringIO object at 0x0000020E57DD3670>
    │         │               │      │      └ <traceback object at 0x0000020E575F7500>
    │         │               │      └ (<class 'OSError'>, OSError(10038, '在一个非套接字上尝试了一个操作。', None, 10038, None), <traceback object at 0x0000020E575F7500>)
    │         │               └ (<class 'OSError'>, OSError(10038, '在一个非套接字上尝试了一个操作。', None, 10038, None), <traceback object at 0x0000020E575F7500>)
    │         └ <function loguru_print_exception at 0x0000020E53D431F0>
    └ <module 'traceback' from 'D:\\Python39\\lib\\traceback.py'>

TypeError: loguru_print_exception() missing 1 required positional argument: 'chain'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\Python39\lib\asyncio\base_events.py", line 1764, in call_exception_handler
    self.default_exception_handler(context)
    │    │                         └ {'message': 'Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)', 'exception': OSError(10038, '在一个非...
    │    └ <function BaseEventLoop.default_exception_handler at 0x0000020E532559D0>
    └ <ProactorEventLoop running=False closed=False debug=False>

  File "D:\Python39\lib\asyncio\base_events.py", line 1738, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
    │      │               │                    └ (<class 'OSError'>, OSError(10038, '在一个非套接字上尝试了一个操作。', None, 10038, None), <traceback object at 0x0000020E575F7500>)
    │      │               └ ['Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)', 'handle: <Handle _ProactorBasePipeTransport....
    │      └ <function Logger.error at 0x0000020E516E6940>
    └ <Logger asyncio (WARNING)>

  File "D:\Python39\lib\logging\__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
    │    │    │      │    │       └ {'exc_info': (<class 'OSError'>, OSError(10038, '在一个非套接字上尝试了一个操作。', None, 10038, None), <traceback object at 0x0000020E575F75...
    │    │    │      │    └ ()
    │    │    │      └ 'Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)\nhandle: <Handle _ProactorBasePipeTransport._ca...
    │    │    └ 40
    │    └ <function Logger._log at 0x0000020E516E6CA0>
    └ <Logger asyncio (WARNING)>

  File "D:\Python39\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
    │    │      └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1738, "Exception in callback _ProactorBasePipeTransport._cal...
    │    └ <function Logger.handle at 0x0000020E516E6D30>
    └ <Logger asyncio (WARNING)>

  File "D:\Python39\lib\logging\__init__.py", line 1599, in handle
    self.callHandlers(record)
    │    │            └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1738, "Exception in callback _ProactorBasePipeTransport._cal...
    │    └ <function Logger.callHandlers at 0x0000020E516E6F70>
    └ <Logger asyncio (WARNING)>

  File "D:\Python39\lib\logging\__init__.py", line 1669, in callHandlers
    lastResort.handle(record)
    │          │      └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1738, "Exception in callback _ProactorBasePipeTransport._cal...
    │          └ <function Handler.handle at 0x0000020E516DF430>
    └ <_StderrHandler <stderr> (WARNING)>

  File "D:\Python39\lib\logging\__init__.py", line 952, in handle
    self.emit(record)
    │    │    └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1738, "Exception in callback _ProactorBasePipeTransport._cal...
    │    └ <function StreamHandler.emit at 0x0000020E516DF8B0>
    └ <_StderrHandler <stderr> (WARNING)>

  File "D:\Python39\lib\logging\__init__.py", line 1091, in emit
    self.handleError(record)
    │    │           └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1738, "Exception in callback _ProactorBasePipeTransport._cal...
    │    └ <function Handler.handleError at 0x0000020E516DF670>
    └ <_StderrHandler <stderr> (WARNING)>

  File "D:\Python39\lib\logging\__init__.py", line 1005, in handleError
    traceback.print_exception(t, v, tb, None, sys.stderr)
    │         │                               │   └ <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
    │         │                               └ <module 'sys' (built-in)>
    │         └ <function loguru_print_exception at 0x0000020E53D431F0>
    └ <module 'traceback' from 'D:\\Python39\\lib\\traceback.py'>

TypeError: loguru_print_exception() missing 1 required positional argument: 'chain'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\Python39\lib\logging\__init__.py", line 1083, in emit
    msg = self.format(record)
          │    │      └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1771, "Exception in default exception handler">
          │    └ <function Handler.format at 0x0000020E516DF310>
          └ <_StderrHandler <stderr> (WARNING)>

  File "D:\Python39\lib\logging\__init__.py", line 927, in format
    return fmt.format(record)
           │   │      └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1771, "Exception in default exception handler">
           │   └ <function Formatter.format at 0x0000020E516E1670>
           └ <logging.Formatter object at 0x0000020E51642940>

  File "D:\Python39\lib\logging\__init__.py", line 671, in format
    record.exc_text = self.formatException(record.exc_info)
    │      │          │    │               │      └ (<class 'TypeError'>, TypeError("loguru_print_exception() missing 1 required positional argument: 'chain'"), <traceback objec...
    │      │          │    │               └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1771, "Exception in default exception handler">
    │      │          │    └ <function Formatter.formatException at 0x0000020E516E1430>
    │      │          └ <logging.Formatter object at 0x0000020E51642940>
    │      └ None
    └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1771, "Exception in default exception handler">

  File "D:\Python39\lib\logging\__init__.py", line 621, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
    │         │               │      │      │         └ <_io.StringIO object at 0x0000020E57DD3DC0>
    │         │               │      │      └ <traceback object at 0x0000020E579EDCC0>
    │         │               │      └ (<class 'TypeError'>, TypeError("loguru_print_exception() missing 1 required positional argument: 'chain'"), <traceback objec...
    │         │               └ (<class 'TypeError'>, TypeError("loguru_print_exception() missing 1 required positional argument: 'chain'"), <traceback objec...
    │         └ <function loguru_print_exception at 0x0000020E53D431F0>
    └ <module 'traceback' from 'D:\\Python39\\lib\\traceback.py'>

TypeError: loguru_print_exception() missing 1 required positional argument: 'chain'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

> File "E:\Code\QQWechat\graia_framework\sakura_ariadne\main.py", line 65, in <module>
    loop.run_until_complete(app.lifecycle())
    │    │                  │   └ <function Ariadne.lifecycle at 0x0000020E54AF5AF0>
    │    │                  └ <graia.ariadne.app.Ariadne object at 0x0000020E55507820>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000020E532541F0>
    └ <ProactorEventLoop running=False closed=False debug=False>

  File "D:\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000020E5330FEE0>
    └ <ProactorEventLoop running=False closed=False debug=False>

  File "D:\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "D:\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000020E53255CA0>
    └ <ProactorEventLoop running=False closed=False debug=False>

  File "D:\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000020E531E6940>
    └ <Handle _ProactorBasePipeTransport._call_connection_lost(None)>

  File "D:\Python39\lib\asyncio\events.py", line 94, in _run
    self._loop.call_exception_handler(context)
    │    │                            └ {'message': 'Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)', 'exception': OSError(10038, '在一个非...
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle _ProactorBasePipeTransport._call_connection_lost(None)>

  File "D:\Python39\lib\asyncio\base_events.py", line 1771, in call_exception_handler
    logger.error('Exception in default exception handler',
    │      └ <function Logger.error at 0x0000020E516E6940>
    └ <Logger asyncio (WARNING)>

  File "D:\Python39\lib\logging\__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
    │    │    │      │    │       └ {'exc_info': True}
    │    │    │      │    └ ()
    │    │    │      └ 'Exception in default exception handler'
    │    │    └ 40
    │    └ <function Logger._log at 0x0000020E516E6CA0>
    └ <Logger asyncio (WARNING)>
  File "D:\Python39\lib\logging\__init__.py", line 1091, in emit
    self.handleError(record)
    │    │           └ <LogRecord: asyncio, 40, D:\Python39\lib\asyncio\base_events.py, 1771, "Exception in default exception handler">
    │    └ <function Handler.handleError at 0x0000020E516DF670>
    └ <_StderrHandler <stderr> (WARNING)>

  File "D:\Python39\lib\logging\__init__.py", line 1005, in handleError
    traceback.print_exception(t, v, tb, None, sys.stderr)
    │         │                               │   └ <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
    │         │                               └ <module 'sys' (built-in)>
    │         └ <function loguru_print_exception at 0x0000020E53D431F0>
    └ <module 'traceback' from 'D:\\Python39\\lib\\traceback.py'>

TypeError: loguru_print_exception() missing 1 required positional argument: 'chain'
```

**如何复现**
等待后续补充

**预期行为**
你希望如何更改/原本应该是怎样的。

**使用环境:**
 - 系统: win11
 - MAH 版本: 2.3.1
 - Ariadne 版本:0.3.9
 - Python 版本:3.9.6
 - 其他 Graia 库版本:
 - 其他 有关 库版本:

**日志/截图**
将任何有关的日志/截图放到这里（控制台输出/MAH输出/...)

**Comment by BlueGlassBlock** [comment]
现在应该不会因为 loguru 退出程序了

**Comment by BlueGlassBlock** [comment]
暂时关闭。
随时可请求再打开。
